services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: ./api
    environment:
      # DB_HOST: ${DB_HOST}
      # DB_USERNAME: ${DB_USERNAME}
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_NAME: ${DB_NAME}
      API_PORT: ${API_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - app-network
    command: |
      sh -c "
        npx prisma generate && \
        npx prisma migrate deploy && \
        npm run build && \
        npm run start
      "

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
